### ISSUE TITLE
will crash。。。。。。。。。。。。。。。。。。。。。。。。。。

### ISSUE THREAD

**Issue by ykzhourui** [rahadian/TONxDAO_aryatux_claimer#1]
will crash。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by rahadian** [comment]
i've checked it then re run the script and everything is working again. So, imo it caused by server of game itself.

**Comment by ykzhourui** [comment]
It could crash in minutes, it could crash in hours...

**Comment by rahadian** [comment]
> It could crash in minutes, it could crash in hours...

aight, please gimme the detail error. because i run in my server and everything is working.
