### ISSUE TITLE
ERROR:core.info:Request Failed: 404

### ISSUE THREAD

**Issue by mainiken** [rahadian/TONxDAO_aryatux_claimer#12]
ERROR:core.info:Request Failed: 404 Client Error: Not Found for url: https://app.production.tonxdao.app/api/v1/dao_users
INFO:core.info:Retrying in 1 seconds...
ERROR:core.info:Request Failed: 404 Client Error: Not Found for url: https://app.production.tonxdao.app/api/v1/dao_users
INFO:core.info:Retrying in 1 seconds...
ERROR:core.info:Request Failed: 404 Client Error: Not Found for url: https://app.production.tonxdao.app/api/v1/dao_users
INFO:core.info:Retrying in 2 seconds...
ERROR:core.info:Request Failed: 404 Client Error: Not Found for url: https://app.production.tonxdao.app/api/v1/dao_users
INFO:core.info:Retrying in 2 seconds...
ERROR:core.info:Request Failed: 404 Client Error: Not Found for url: https://app.production.tonxdao.app/api/v1/dao_users
ERROR:core.info:Request Failed: 404 Client Error: Not Found for url: https://app.production.tonxdao.app/api/v1/dao_users
An error occurred: 404 Client Error: Not Found for url: https://app.production.tonxdao.app/api/v1/dao_users

**Comment by rahadian** [comment]
updated.
