### ISSUE TITLE
err0r

### ISSUE THREAD

**Issue by AntiWarforever** [rahadian/TONxDAO_aryatux_claimer#2]
▄▄▄       ██▀███ ▓██   ██▓ ▄▄▄     ▄▄▄█████▓ █    ██ ▒██   ██▒
▒████▄    ▓██ ▒ ██▒▒██  ██▒▒████▄   ▓  ██▒ ▓▒ ██  ▓██▒▒▒ █ █ ▒░
▒██  ▀█▄  ▓██ ░▄█ ▒ ▒██ ██░▒██  ▀█▄ ▒ ▓██░ ▒░▓██  ▒██░░░  █   ░
░██▄▄▄▄██ ▒██▀▀█▄   ░ ▐██▓░░██▄▄▄▄██░ ▓██▓ ░ ▓▓█  ░██░ ░ █ █ ▒
 ▓█   ▓██▒░██▓ ▒██▒ ░ ██▒▓░ ▓█   ▓██▒ ▒██▒ ░ ▒▒█████▓ ▒██▒ ▒██▒
 ▒▒   ▓▒█░░ ▒▓ ░▒▓░  ██▒▒▒  ▒▒   ▓▒█░ ▒ ░░   ░▒▓▒ ▒ ▒ ▒▒ ░ ░▓ ░
  ▒   ▒▒ ░  ░▒ ░ ▒░▓██ ░▒░   ▒   ▒▒ ░   ░    ░░▒░ ░ ░ ░░   ░▒ ░
  ░   ▒     ░░   ░ ▒ ▒ ░░    ░   ▒    ░       ░░░ ░ ░  ░    ░
      ░  ░   ░     ░ ░           ░  ░           ░      ░    ░
                   ░ ░                                                                                                  

07-10-2024 08:31:33
All users have low energy, pausing for 4 hours...

**Comment by rahadian** [comment]
can you gimme the detail output ?

**Comment by AntiWarforever** [comment]
I first time run get just this error
```
07-10-2024 08:39:42
All users have low energy, pausing for 4 hours...
```

**Comment by rahadian** [comment]
are you already input the user auth in data.txt?

**Comment by AntiWarforever** [comment]
Userdata1=***
Userdata2=***
...
(every data in next line woth out every thing like semicolon)
Just i use windscribe vpn
It seems to be the problem

**Comment by rahadian** [comment]
in data.txt must be contain like this :
user=***

or if you have more than one user it should be like this:
user=***
user=***
