### ISSUE TITLE
thanks & multi threading please

### ISSUE THREAD

**Issue by AntiWarforever** [rahadian/TONxDAO_aryatux_claimer#4]
First of all, I want to thank you for making such a beautiful thing
I have 47 account but 1 account work in one time , this take more time
It starts consuming energy from 1000 (each account will reduce 5 by 5 energy)
can you set a multi threading please?
see 1 account start from 4:43 and finish in 5:14 (around 35 min for a account need time , don't enough for 47 account)
![image](https://github.com/user-attachments/assets/a461f758-0f00-4f66-8168-5e2bd7634c2b)
![image](https://github.com/user-attachments/assets/67461b02-0945-4ca0-b4db-81165d65152a)

**Comment by rahadian** [comment]
already updated, you can try it out

**Comment by AntiWarforever** [comment]
> already updated, you can try it out

Very very thanks & work correct ❤️
