### ISSUE TITLE
dose the code give 3x ?

### ISSUE THREAD

**Issue by Ahdsalah121** [rahadian/TONxDAO_aryatux_claimer#5]
dose the code make all the account tap in the same time?

**Comment by rahadian** [comment]
what's you mean with 3x ?
yes, all account you insert in data.txt will execute in same time.

**Comment by unkby** [comment]
In the game, if three players start playing at the same time, then a coefficient of x3 appears

> what's you mean with 3x ? yes, all account you insert in data.txt will execute in same time.
